import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/Share/Header'
import Footer from '@/components/Share/Footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AATA KA LO GUYS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
